version: '3.3'
services:
  django:
    build:
      context: ./app
      dockerfile: ./Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      database:
          condition: service_healthy
   
  database:
    image: postgres
    volumes:
      - ./database/postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - django
    links:
      - django:django

volumes:
  postgres_data:
  static_volume:
  media_volume: